GRANT ALL PRIVILEGES ON world . * TO 'trinity'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON characters . * TO 'trinity'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON auth . * TO 'trinity'@'%' WITH GRANT OPTION;